app_lesson:
    path:     /
    defaults: { _controller: AppFrontBundle:Lesson:lesson }
    methods: GET
lesson_show_matieres:
    path:     /matieres
    defaults: { _controller: "AppFrontBundle:Lesson:showMatieres" }
    methods: GET
lesson_show_cours:
    path:     /cours
    defaults: { _controller: "AppFrontBundle:Lesson:showCours" }
    methods: GET
lesson_add_cours:
    path:     /add-cours
    defaults: { _controller: "AppFrontBundle:Lesson:addCours" }
    methods: GET
lesson_associer_cours_matiere:
    path:     /associer-cours-matiere
    defaults: { _controller: "AppFrontBundle:Lesson:associerCoursMatiere" }
    methods: GET
lesson_associer_eleve_filiere:
    path:     /associer-eleve-filiere
    defaults: { _controller: "AppFrontBundle:Lesson:associerEleveFiliere" }
    methods: GET
lesson_edit_cours:
    path:     /edit-cours
    defaults: { _controller: "AppFrontBundle:Lesson:editCours" }
    methods: GET
