app_front:
    resource: "@AppFrontBundle/Resources/config/routing.yml"
    prefix:   /
logout:
    path: /logout

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"