app_homepage:
    path:     /
    defaults: { _controller: AppFrontBundle:Default:index }
app_lesson:
    resource: "@AppFrontBundle/Resources/config/routing/routing-lesson.yml"
    prefix: /lesson
app_planning:
    path:     /planning
    defaults: { _controller: AppFrontBundle:Planning:planning }
app_contact:
    path:     /contact
    defaults: { _controller: AppFrontBundle:Contact:contact }
