app_homepage:
    path:     /
    defaults: { _controller: AppFrontBundle:Default:index }
app_lesson:
    resource: "@AppFrontBundle/Resources/config/routing/routing-lesson.yml"
    prefix: /lesson
app_planning:
    resource: "@AppFrontBundle/Resources/config/routing/routing.yml"
    prefix: /planning
app_contact:
    path:     /{langue}/contact
    defaults: { _controller: AppFrontBundle:Contact:contact }
