app_homepage:
    path:     /
    defaults: { _controller: AppFrontBundle:Default:index }
app_lesson:
    path:     /lesson
    defaults: { _controller: AppFrontBundle:Lesson:lesson }
app_planning:
    resource: "@AppFrontBundle/Resources/config/routing/routing.yml"
    prefix: /planning
app_contact:
    path:     /contact
    defaults: { _controller: AppFrontBundle:Contact:contact }
